#ifndef LMPI_CONSTANTS_H
#define LMPI_CONSTANTS_H

enum {
    LMPI_SEND_OP = 0,
    LMPI_RECV_OP = 1
};

enum {
    LMPI_STATUS_COMPLETED   = 0,
    LMPI_STATUS_PENDING     = 1,
    LMPI_STATUS_IN_PROGRESS = 2,
    LMPI_STATUS_WAITING     = 3
};

enum {
    SLOT_EMPTY    = 0,
    SLOT_RESERVED = 2,
    SLOT_READY    = 1
};

enum {
    LMPI_SUCCESS = 0,
    LMPI_ERR_BUFFER,
    LMPI_ERR_COUNT,
    LMPI_ERR_TYPE,
    LMPI_ERR_TAG,
    LMPI_ERR_COMM,
    LMPI_ERR_RANK,
    LMPI_ERR_REQUEST,
    LMPI_ERR_ROOT,
    LMPI_ERR_GROUP,
    LMPI_ERR_OP,
    LMPI_ERR_TOPOLOGY,
    LMPI_ERR_DIMS,
    LMPI_ERR_ARG,
    LMPI_ERR_UNKNOWN,
    LMPI_ERR_TRUNCATE,
    LMPI_ERR_OTHER,
    LMPI_ERR_INTERN,
    LMPI_ERR_IN_STATUS,
    LMPI_ERR_PENDING,
    LMPI_ERR_ACCESS,
    LMPI_ERR_AMODE,
    LMPI_ERR_ASSERT,
    LMPI_ERR_BAD_FILE,
    LMPI_ERR_BASE,
    LMPI_ERR_CONVERSION,
    LMPI_ERR_DISP,
    LMPI_ERR_DUP_DATAREP,
    LMPI_ERR_FILE_EXISTS,
    LMPI_ERR_PROGRESS,
    LMPI_ERR_SYS_COMMAND
};

enum {
    LMPI_EXIT=54321
};

enum {
    LMPI_FIN='f',
    LMPI_RTS='r'
};

#endif

